branch-defaults:
  master:
    environment: backend-v3-dev
    group_suffix: null
global:
  application_name: backend_v3
  branch: null
  default_ec2_keyname: eb-tn
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: tn
  repository: null
  sc: git
  workspace_type: Application
